name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  # You can also trigger this workflow manually from the GitHub UI
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.askhan889971@gmail.com }}
        password: ${{ secrets.SystemX@3250 }}

    - name: Build Docker image
      run: |
        docker build -t your-dockerhub-askhan889971@gmail.com/word-app:latest .

    - name: Push Docker image to Docker Hub
      run: |
        docker push askhan889971@gmail.com/word-app:latest
